# -*- coding: utf-8 -*-
"""Duplicated_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12oeLOIZ_6nqXl6X9yUrahNFYHio2wHq3
"""

from google.colab import drive
drive.mount('/content/drive')

"""# 🐍 **Maestría en Inteligencia Artificial y Analítica de Datos** 🐍

Asignatura: *Programación para Analítica Descriptiva y Predictiva*

* Semestre: Enero-Junio 2026
* Profesor: Dr. Vicente García Jiménez
* Alumno: Ricardo Solano Monje
* Matrícula: 266221
* Unidad 2.
* Prácticas: 19, Limpieza y Transformación de Datos Duplicados o repetidos.
* Objetivo de la práctica: El objetivo de esta actividad es que los estudiantes practiquen los temas vistos de limpieza y transformación de datos duplicados, utilizando un dataset particular con Pandas en Python.
* Realizado por: Ricardo Solano Monje
"""

import pandas as pd
from IPython.display import display, Markdown
from datetime import date
from datetime import datetime
from zoneinfo import ZoneInfo

time_zone = ZoneInfo('America/Ciudad_Juarez')
current_time_aware = datetime.now(time_zone)

display(Markdown(f"### Current time in Cd. Juárez, Chih.: {current_time_aware.strftime('%H:%M:%S')}"))
formatted_date = datetime.now(time_zone).strftime("%B %d, %Y")
display(Markdown(f"### Today's date: {formatted_date}"))

from IPython.display import display, Markdown
def eprint(text_type,markdown_text) -> None:
    display(Markdown(text_type+" "+markdown_text))
    pass #return None

def hprint(text,header_width) ->None:
    print("="*header_width)
    print(f"{text:^{header_width}}")
    print("="*header_width)
    pass # return None

"""# Ejercicio 1
### Duplicidad Parcial Una columna: Contar y Filtrar los registros duplicados en Duration

* Carga el conjunto de datos dirtydata.csv y verifica que su carga sea correcta.
* Cuenta la cantidad de registros duplicados utilizando solo la información de columna Duration e imprime
* Utiliza value_counts() e imprime la cantidad de registros que hay por cada valor único.
* Filtra los datos y obten los registros sin duplicados

"""

import pandas as pd

def load_data(file_path) -> pd.DataFrame | None:
    """
    Load the dirtydata.csv dataset
    """
    try:
        df = pd.read_csv(file_path)
        print("Data loaded successfully!")
        print(f"Dataset shape: {df.shape}")
        return df
    except FileNotFoundError:
        print(f"Error: File not found at {file_path}")
        pass #return None

def count_duration_duplicates(df) -> float:
    """
    Count duplicate records using only the Duration column
    """
    # Count total duplicates in Duration column
    duration_duplicates = df.duplicated(subset=['Duration']).sum()
    return duration_duplicates

def display_value_counts(df) -> pd.DataFrame:
    """
    Use value_counts() to show records for each unique value in Duration
    """
    print("-"*50)
    print("Number of records for each unique Duration value:")
    print("-"*50)
    value_counts = df['Duration'].value_counts().sort_index()
    print(value_counts)
    return value_counts

def remove_duration_duplicates(df) -> pd.DataFrame| pd.DataFrame:
    """
    Filter data to obtain records without duplicates based on Duration
    """
    df_no_duplicates = df.drop_duplicates(subset=['Duration'])
    not_df_no_duplicates=df[~df.duplicated(subset=['Duration'])]
    print("-"*50)
    print(f"Records without duplicates shape: {df_no_duplicates.shape}")
    print("-"*50)
    # df_no_duplicates,not_df_no_duplicates can be used for further analysis: df_no_duplicates['Pulse'].mean() = 109.3
    return df_no_duplicates,not_df_no_duplicates

def main() -> tuple[pd.DataFrame| None, pd.DataFrame| None]:
    """
    Main function to execute all tasks
    """
    # File path
    file_path = 'drive/MyDrive/ClassFiles/dirtydata.csv'

    # 1. Load the dataset
    eprint("*","STEP 1: Load dataset, verify success")
    df = load_data(file_path)
    print(df.head(5))
    if df is not None:
        # 2. Count duplicate records using Duration column, remember to use subset option
        duration_duplicates=count_duration_duplicates(df)
        print("-"*50)
        eprint("*",f"STEP 2: Number of duplicate records based on Duration column: {duration_duplicates}")
        print("-"*50)
        # 3. Use value_counts() to show records for each unique value
        eprint("*","STEP 3: Use value_counts() to show the number of records for each unique value")
        display_value_counts(df)

        #  STEP 4. Filter to get records without duplicates
        eprint("*","STEP 4. Filter to get records without duplicates")
        df_no_duplicates,not_df_no_duplicates = remove_duration_duplicates(df)
        print("CLEAN-PERSISTENT DATASET, NO DUPLICATES: df_no_duplicates = df.drop_duplicates(subset=['Duration'])")
        print(df_no_duplicates.head(4))
        print("SIMPLEST WAY TO SHOW NO DUPLICATES: df[~df.duplicated(subset=['Duration'])]:")
        print(not_df_no_duplicates.head(4))

        return df, df_no_duplicates
    else:
        pass #return None, None

if __name__ == "__main__":
    df, df_no_duplicates = main()

    # Optional: Display summary
    if df is not None:
        hprint("DataFrame's shape after filtering duplicates: ",80)
        print(f"Original dataset shape: {df.shape}",80)
        print(f"Cleaned dataset shape: {df_no_duplicates.shape}")
        print(f"Records removed: {len(df) - len(df_no_duplicates)}")

"""# Ejercicio 2
### Duplicidad Parcial Dos columnas: Contar y Filtrar los registros duplicados en Pulse y MaxPulse

* Carga el conjunto de datos dirtydata.csv y verifica que su carga sea correcta.
* Cuenta la cantidad de registros duplicados utilizando la información de las columnas Pulse y Maxpulse
* Utiliza value_counts() e imprime la cantidad de registros que hay por cada valor único.
* Filtra los datos y obten los registros cuando keep = 'last'
"""

import pandas as pd

def load_data(file_path) -> pd.DataFrame | None:
    """
    Load the dirtydata.csv dataset
    """
    try:
        df = pd.read_csv(file_path)
        print(f"Dataset shape: {df.shape}")
        print(f"Columns: {list(df.columns)}")
        print("\nFirst 5 rows:")
        print(df.head())
        return df
    except FileNotFoundError:
        print(f"Error: File not found at {file_path}")
        pass #return None

def count_pulse_maxpulse_duplicates(df):
    """
    Count duplicate records using Pulse and Maxpulse columns
    Note: Using 'Maxpulse' as per the actual column name in your data
    """
    # Count duplicates based on Pulse and Maxpulse columns
    pulse_maxpulse_duplicates = df.duplicated(subset=['Pulse', 'Maxpulse']).sum()
    print(f"\nNumber of duplicate records based on Pulse and Maxpulse columns: {pulse_maxpulse_duplicates}")

    # Show the actual duplicate combinations
    duplicate_mask = df.duplicated(subset=['Pulse', 'Maxpulse'], keep=False)
    duplicates = df[duplicate_mask].sort_values(['Pulse', 'Maxpulse'])

    if not duplicates.empty:
        print("\nDuplicate combinations found:")
        print(duplicates[['Pulse', 'Maxpulse']].to_string(index=False))

    return pulse_maxpulse_duplicates

def display_df_value_counts(df) -> pd.DataFrame:
    """
    Use value_counts() to show records for each unique value in Duration
    """
    print("-"*50)
    print("Number of records for all DataFrame:")
    print("-"*50)
    value_counts = df.value_counts().sort_index()
    print(value_counts)
    return value_counts

def display_value_counts(df):
    """
    Use value_counts() to show records for each unique combination of Pulse and Maxpulse
    value counts as list:
    list(value_counts.items())=[((90, 112), 1), ((92, 115), 1), ((92, 118), 1), ((97, 125), 1),
                       ((98, 120), 1), ((98, 123), 1), ((98, 124), 1), ((100, 119), 1),
                       ((100, 120), 4), ((100, 132), 1), ((102, 126), 1), ((102, 127), 1),
                       ((102, 129), 1), ((103, 123), 1), ((103, 132), 1), ((103, 135), 1),
                       ((103, 147), 1), ((104, 132), 1)]
    """


    # Using value_counts() on DataFrame subset - much cleaner and professional

    value_counts = df[['Pulse', 'Maxpulse']].value_counts().sort_index()

    print("-"*60)
    print(f"The hierarchical display of different values and their counting of 2 columns handled by Pandas")
    print("-"*60)
    print(f"{value_counts}")
    print("-"*60)
    print(f"The tuples list display of different values and their counting")
    print("-"*60)
    print(f"{list(value_counts.items())}")
    print("-"*60)
    print("The readable display iterating through ABOVE value_counts tuples for printing the different values and their counting:")
    print("-"*60)
    # Display in a readable format
    for (pulse, maxpulse), count in value_counts.items():
        print(f"Pulse: {pulse} & Maxpulse: {maxpulse} = {count} record(s)")

    print(f"\nTotal unique combinations: {len(value_counts)}")
    return value_counts

def filter_keep_last(df):
    """
    Filter data to retrieve records where keep = 'last' (keeping last occurrence of duplicates)
    """
    # Keep last occurrence of each duplicate combination
    df_last_keep = df.drop_duplicates(subset=['Pulse', 'Maxpulse'], keep='last')
    print(f"Original dataset shape: {df.shape}")
    print(f"Cleaned dataset shape (keep='last'): {df_last_keep.shape}")
    print(f"Records removed: {len(df) - len(df_last_keep)}")
   # print(f"\nRecords after keeping last occurrence of duplicates:")
    #print(f"Shape: {df_last_keep.shape}")

    # Show detailed information about duplicates and which ones were kept
    duplicate_mask = df.duplicated(subset=['Pulse', 'Maxpulse'], keep=False)
    duplicates = df[duplicate_mask].sort_values(['Pulse', 'Maxpulse'])

    if not duplicates.empty:
        hprint("DETAILED DUPLICATE RECORDS",80)

        """
        Group these duplicates by Pulse and Maxpulse combinations to show all occurrences
        This creates separate groups for each unique (Pulse, Maxpulse) pair


            Pulse  Maxpulse  Duration          Date  Calories
        11    100       120        60  '2020/12/12'     250.7
        12    100       120        60  '2020/12/12'     250.7
        17    100       120        60  '2020/12/17'     300.0
        26    100       120        60      20201226     250.0

        idx = the index number (11, 12, 17, 26)
        row = the entire row data as a Series
        Check if this is the last index in the group
        group.index returns: [11, 12, 17, 26]
        group.index[-1] returns: 26 = keep 'last'
        Loop iterations:
            Iteration 1: idx=11, is it == 26? NO → "REMOVED"
            Iteration 2: idx=12, is it == 26? NO → "REMOVED"
            Iteration 3: idx=17, is it == 26? NO → "REMOVED"
            Iteration 4: idx=26, is it == 26? YES → "KEPT (last occurrence)"
        """
        for (pulse, maxpulse), group in duplicates.groupby(['Pulse', 'Maxpulse']):
            print(f"\nPulse: {pulse}, Maxpulse: {maxpulse}")
            print(f"Total occurrences: {len(group)}")
            print("All indices and their data:")

            for idx, row in group.iterrows():
                keep_status = "KEPT (last occurrence)" if idx == group.index[-1] else "REMOVED"
                print(f"  Index {idx}: Duration={row['Duration']}, Date={row['Date']}, "
                f"Pulse={row['Pulse']}, Maxpulse={row['Maxpulse']}, "
                f"Calories={row['Calories']} -> {keep_status}")

    return df_last_keep

def main() -> tuple[pd.DataFrame| None, pd.DataFrame| None]:
    """
    Main function to execute all tasks
    """
    # File path
    file_path = 'drive/MyDrive/ClassFiles/dirtydata.csv'

    # 1. Load the dataset
    eprint("*","STEP 1: Load dataset, verify success")
    df = load_data(file_path)
    if df is not None:
        print("="*60)
        eprint("*","Step 2: COUNT DUPLICATES")
        print("="*60)
        # 2. Count duplicate records using Pulse and Maxpulse columns
        duplicate_count = count_pulse_maxpulse_duplicates(df)

        print("="*60)
        eprint("*","Step 3: VALUE COUNTS")
         # 3. Use value_counts() to show records for each unique value
        print("Use value_counts() to show records for each unique value")
        print("="*60)
        display_df_value_counts(df)
        print("-"*60)
        print("Number of records for each unique Pulse-Maxpulse combination.")
        print("Using value_counts() on 2 columns becomes a MultiIndex Series.")
        print("="*60)
        # 3. Use value_counts() to show records for each unique combination
       # print("-"*60)
        value_counts = display_value_counts(df)

        print("="*60)
        eprint("*","Step 4: FILTER WITH KEEP='LAST'")
        print("="*60)
        # 4. Filter to get records where keep = 'last'
        df_clean = filter_keep_last(df)

        return df, df_clean
    else:
        return None, None

if __name__ == "__main__":
    df, df_clean = main()

"""# Ejercicio 3
### Duplicidad Total o Exacta: Contar y Filtrar los registros duplicados

* Carga el conjunto de datos dirtydata.csv y verifica que su carga sea correcta.
* Cuenta la cantidad de registros duplicados exactos (todas las columnas)
* Utiliza sum() e imprime la cantidad de registros con duplicidad exacta
* Filtra los datos y obten los registros cuando keep = 'last'
"""

import pandas as pd

def load_data(file_path) -> pd.DataFrame | None:
    """
    Load the dirtydata.csv dataset
    """
    try:
        df = pd.read_csv(file_path)
        print("Data loaded successfully!")
        print(f"Dataset shape: {df.shape}")
        print(f"Columns: {list(df.columns)}")
        print("\nFirst 5 rows:")
        print(df.head())
        return df
    except FileNotFoundError:
        print(f"Error: File not found at {file_path}")
        pass #return None

def sum_exact_duplicates(df):
    """
    Count the number of exact duplicate records (all columns)
    Using duplicated() with default subset=None (all columns)
    """
    # Count exact duplicates (all columns)
    exact_duplicates_count = df.duplicated().sum()
    print(f"Number of exact duplicate records (all columns) using sum() over duplicates(): {exact_duplicates_count}")

    # Show the duplicate records if any exist
    if exact_duplicates_count > 0:
        duplicate_mask = df.duplicated(keep=False)
        duplicates = df[duplicate_mask].sort_values(by=list(df.columns)) #list returns ['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories']
                                                                        # So, sort by all columns
        print(f"\nExact duplicate records found:")
        print(duplicates.to_string(index=False))


    return exact_duplicates_count

def count_exact_duplicates(df):
    """
    Use sum() to print the number of records with exact duplicates
    This is essentially the same as count_exact_duplicates but
    explicitly using sum() on the boolean Series
    """

    #exact_duplicates_sum = df.duplicated().sum()
    # print(f"Using sum() over duplicates() - Number of exact duplicate records: {exact_duplicates_sum}")

    # Using sum() on the boolean Series from duplicated()
    # Alternative: Show the boolean mask sum
    duplicate_mask = df.duplicated()
    print(f"Boolean mask values (True=duplicate):")
    print(duplicate_mask.tolist())
    print("-"*80)
    print(f"Using sum() over Boolean mask -Number of exact duplicate records: {duplicate_mask.sum()}")
    print("-"*80)
    return duplicate_mask.sum()

def filter_keep_last(df):
    """
    Filter data to retrieve records where keep = 'last'
    Keeping the last occurrence of exact duplicates
    """
    # Keep last occurrence of exact duplicates (all columns)
    df_last_keep = df.drop_duplicates(keep='last')

    print(f"\nRecords after keeping last occurrence of exact duplicates:")
    print(f"Shape: {df_last_keep.shape}")
    print(f"Records removed: {len(df) - len(df_last_keep)}")

    # Show detailed information about duplicates if any exist
    duplicate_mask = df.duplicated(keep=False)
    if duplicate_mask.any():
        hprint("DETAILED DUPLICATE ANALYSIS",80)

        # Get all duplicate records
        duplicates = df[duplicate_mask].sort_values(by=list(df.columns))

        # Group by all columns to find exact matches
        # Convert to tuple of values for grouping
        duplicate_groups = duplicates.groupby(list(duplicates.columns))

        for group_values, group in duplicate_groups:
            print(f"\nExact duplicate group (appears {len(group)} times):")
            print("All occurrences:")
            for idx, row in group.iterrows():
                keep_status = "KEPT (last occurrence)" if idx == group.index[-1] else "REMOVED"
                print(f"  Index {idx}: {keep_status}")
                print(f"    {row.to_dict()}")

    return df_last_keep

def main() -> tuple[pd.DataFrame| None, pd.DataFrame| None]:
    """
    Main function to execute all tasks
    """
    # File path
    file_path = 'drive/MyDrive/ClassFiles/dirtydata.csv'

    # 1. Load the dataset
    eprint("*","STEP 1: Load dataset, verify success")
    df = load_data(file_path)
    if df is not None:
        print("\n" + "="*60)
        eprint("*","TASK 2: COUNT exact duplicates")
        print("="*60)
        # 2. Count the number of exact duplicate records
        duplicate_count = count_exact_duplicates(df)
        print("\n" + "="*60)
        eprint("*","TASK 3: USE .sum() to print duplicates")
        print("="*60)
        # 3. Use sum() to print the number of records with exact duplicates
        duplicate_sum = sum_exact_duplicates(df)
        print("\n" + "="*60)
        eprint("*","TASK 4: FILTERING DataFrame with keep='last'")
        print("="*60)
        # 4. Filter to get records where keep = 'last'
        df_clean = filter_keep_last(df)

        return df, df_clean
    else:
        return None, None

if __name__ == "__main__":
    df, cleaned_data = main()

"""# Ejercicio 4
### Cálculo de la media con duplicados y sin duplicados

* Carga el conjunto de datos dirty.csv y verifica que su carga sea correcta.
* Calcula e imprime la media de las columnas Pulse y MaxPulse
* Identifica los valores duplicados en las columnas Pulse y MaxPulse (Duplicidad Parcial) y elimina los registro repetidos. Quédate con las últimas ocurrencias
* Utiliza el conjunto anterior sin datos duplicados (recuerda que solo quedaron las últimas ocurrencias de los datos) y calcula la media de las columnas Pulse y MaxPulse
"""

import pandas as pd

def load_data(file_path) ->pd.DataFrame:
    """
    Load the dirtydata.csv dataset
    """
    try:
        df = pd.read_csv(file_path)
        print("Data loaded successfully!")
        print(f"Dataset shape: {df.shape}")
        print(f"Columns: {list(df.columns)}")
        print("\nFirst 5 rows:")
        print(df.head())
        return df
    except FileNotFoundError:
        print(f"Error: File not found at {file_path}")
        pass #return None

def calculate_original_mean(df) -> float | float:
    """
    Calculate and print the mean of Pulse and Maxpulse columns from original data
    """
    print("\n" + "="*60)
    print("MEAN OF ORIGINAL DATA - possibly WITH DUPLICATES")
    print("="*60)

    pulse_mean = df['Pulse'].mean()
    maxpulse_mean = df['Maxpulse'].mean()

    print(f"Pulse mean (with duplicates): {pulse_mean:.2f}")
    print(f"Maxpulse mean (with duplicates): {maxpulse_mean:.2f}")

    # Show additional statistics
    print(f"\nAdditional info:")
    print(f"Total records used: {len(df)}")
    print(f"Pulse - min: {df['Pulse'].min()}, max: {df['Pulse'].max()}")
    print(f"Maxpulse - min: {df['Maxpulse'].min()}, max: {df['Maxpulse'].max()}")

    return pulse_mean, maxpulse_mean

def remove_partial_duplicates(df) ->pd.DataFrame:
    """
    Identify duplicate values in Pulse and Maxpulse columns (Partial Duplication)
    and remove repeated records, keeping the last occurrences
    """
    print("\n" + "="*60)
    print("REMOVING PARTIAL DUPLICATES")
    print("="*60)

    # Count duplicates before removal
    duplicate_count = df.duplicated(subset=['Pulse', 'Maxpulse']).sum()
    print(f"Number of duplicate records based on Pulse and Maxpulse: {duplicate_count}")
    """
    # Show duplicate combinations
    duplicate_mask = df.duplicated(subset=['Pulse', 'Maxpulse'], keep=False)
    if duplicate_mask.any():
        print("\nDuplicate combinations found:")
        duplicates = df[duplicate_mask].sort_values(['Pulse', 'Maxpulse'])
        # Show unique combinations that have duplicates
        dup_combinations = duplicates[['Pulse', 'Maxpulse']].drop_duplicates()
        for _, row in dup_combinations.iterrows():
            count = len(duplicates[(duplicates['Pulse'] == row['Pulse']) &
                                  (duplicates['Maxpulse'] == row['Maxpulse'])])
            print(f"  Pulse={row['Pulse']}, Maxpulse={row['Maxpulse']} appears {count} times")
    """
    # Remove duplicates keeping last occurrence
    df_no_duplicates = df.drop_duplicates(subset=['Pulse', 'Maxpulse'], keep='last')

    print(f"\nAfter removing duplicates (keep='last'):")
    print(f"Original shape: {df.shape}")
    print(f"New shape: {df_no_duplicates.shape}")
    print(f"Records removed: {len(df) - len(df_no_duplicates)}")

    return df_no_duplicates

def calculate_clean_mean(df_clean):
    """
    Calculate the mean of Pulse and Maxpulse columns from data without duplicates
    """
    print("\n" + "="*60)
    print("MEAN OF DATA WITHOUT DUPLICATES")
    print("-"*60)

    pulse_mean_clean = df_clean['Pulse'].mean()
    maxpulse_mean_clean = df_clean['Maxpulse'].mean()

    print(f"Pulse mean (without duplicates): {pulse_mean_clean:.2f}")
    print(f"Maxpulse mean (without duplicates): {maxpulse_mean_clean:.2f}")

    # Show additional statistics
    print(f"\nAdditional info:")
    print(f"Total records used: {len(df_clean)}")
    print(f"Pulse - min: {df_clean['Pulse'].min()}, max: {df_clean['Pulse'].max()}")
    print(f"Maxpulse - min: {df_clean['Maxpulse'].min()}, max: {df_clean['Maxpulse'].max()}")

    return pulse_mean_clean, maxpulse_mean_clean

def compare_means(original_means, clean_means) ->None:
    """
    Compare the means before and after removing duplicates
    """
    print("\n" + "="*60)
    print("ABSOLUTE CHANGE (in original units)")
    print("-"*60)

    pulse_orig_means, maxpulse_orig_means = original_means
    pulse_clean_means, maxpulse_clean_means = clean_means

    pulse_diff_means = pulse_clean_means - pulse_orig_means
    maxpulse_diff_means = maxpulse_clean_means - maxpulse_orig_means

    print(f"Pulse: {pulse_orig_means:.2f} → {pulse_clean_means:.2f} (change: {pulse_diff_means:+.2f})")
    print(f"Maxpulse: {maxpulse_orig_means:.2f} → {maxpulse_clean_means:.2f} (change: {maxpulse_diff_means:+.2f})")

    # Calculate percentage change
    pulse_means_pct = (pulse_diff_means / pulse_orig_means) * 100
    maxpulse_means_pct = (maxpulse_diff_means / maxpulse_orig_means) * 100


    # Relative changed
    # This shows: How much did the mean change relative to the original value?
    pulse_change_pct = (pulse_clean_means - pulse_orig_means) / pulse_orig_means * 100
    maxpulse_change_pct = (maxpulse_clean_means - maxpulse_orig_means) / maxpulse_orig_means * 100
    print("="*60)
    print("HOW MUCH DID THE MEAN CHANGE RELATIVE TO THE ORIGINAL VALUE?")
    print("RELATIVE CHANGE (as percentage)")
    print("-"*60)
    print(f"Pulse mean changed by {pulse_change_pct:+.2f}% after removing duplicates")
    print(f"Maxpulse mean changed by {maxpulse_change_pct:+.2f}% after removing duplicates")
    print("-"*60)
    pass
def main() -> tuple[pd.DataFrame| None, pd.DataFrame| None]:
    """
    Main function to execute all tasks
    """
    # File path
    file_path = 'drive/MyDrive/ClassFiles/dirtydata.csv'

    # 1. Load the dataset
    eprint("*","STEP 1: Load the dataset and verify")
    df = load_data(file_path)

    if df is not None:
        # 2. Calculate mean of Pulse and Maxpulse from original data
        eprint("*","STEP 2: Calculate mean of Pulse and Maxpulse from original data")
        original_means = calculate_original_mean(df)

        # 3. Identify and remove partial duplicates (keep last)
        eprint("*","STEP 3: Identify and remove partial duplicates, keeping last")
        df_no_duplicates = remove_partial_duplicates(df)

        # 4. Calculate mean from clean data without duplicates
        eprint("*","STEP 4: Calculate mean of Pulse and Maxpulse from cleaned data (no partial duplicates)")
        clean_means = calculate_clean_mean(df_no_duplicates)

        # Optional: Compare the results
        compare_means(original_means, clean_means)
        return df, df_no_duplicates
    else:
        return None, None

if __name__ == "__main__":
    df, df_no_duplicates = main()